### PR TITLE
option to set time out

### PR DESCRIPTION
**Pull request by sbmadhav**
This should fix Issue #35

### CODE REVIEW

**Comment by sbmadhav** [comment]
@stefanjudis any updates on this pull request ?

**Comment by stefanjudis** [comment]
@sbmadhav Looks good to me... Can release a new version during the day if you need it urgently. :)

**Comment by sbmadhav** [comment]
not urgent. Take your time. Meanwhile I'll work on the threshold issue as well.

**Comment by sbmadhav** [comment]
@stefanjudis  - was this pull request pushed to npm ?

**Comment by stefanjudis** [comment]
Hmm... don't think so... let me check.

Sorry about that. :)

**Comment by stefanjudis** [comment]
@sbmadhav Nope - will do it now... sorry. forgot about it. :-\

**Comment by stefanjudis** [comment]
@sbmadhav Done. :)

**Pull request merged**
