### PR TITLE
Add ability to filter images

### PR DESCRIPTION
**Pull request by danielhusar**
Hey, I have added ability to show only modified screenshots :)
Currently it works only for canvas, as image magic is little more complicated (maybe crate some json with changes there ?)

This is how it looks like:
screen shot 2015-01-20 at 11 58 48

Partially fixes: #32 

@stefanjudis what you think ?

### CODE REVIEW

**Comment by stefanjudis** [comment]
Loving it. :) 

But would also only go with it, when it's supported for all options.
As far as I know imagemagick can also evaluate number of different pixels and stuff. :)

**Comment by danielhusar** [comment]
Ah sorry, I usually don't pay attention to spaces/tabs as editor config solve this, will fix it.

Ok I will try to came with something for the image magic as well.

**Comment by stefanjudis** [comment]
Great!

yeah - editor config is not looking for spaces regarding coding style isn't it? JSCS is a nice thing, I've got included in different projects. 

We might also think of putting it in here. 

Thanks. :)

**Comment by stefanjudis** [comment]
@danielhusar 

Do we want to finish this one day? No pressure, but if not I'll close the PR.

**Comment by danielhusar** [comment]
Hey,

Yeah I hope so :)
I'm usually quite busy at my job but I wil ltry to do it next time I have some time off :)

**Comment by stefanjudis** [comment]
Ja, no pressure. :)

Just wanted to check, because I also have rarely time.

**Comment by stefanjudis** [comment]
Closing due to inactivity.

**Comment by sbmadhav** [comment]
was this merged  to master ? How to configure threshold ?

**Comment by stefanjudis** [comment]
@sbmadhav Nope - was not finished due to inactivity. Sorry.

**Comment by sbmadhav** [comment]
Let me see if I can contribute to this. No commitments yet. But this is something I need.

**Pull request closed without merging**
